name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build native libs
        run: python build_scripts/indigo-release-libs.py
      - name: Build wrappers
        run: python build_scripts/indigo-make-by-libs.py --type=python,java
      - name: Test
        run: python api/tests/python/test.py -j junit_report.xml
      - name: Test report
        if: ${{ always() }}
        run: cat junit_report.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          comment_title: Unit Test Statistics
          hide_comments: all but latest
          files: junit_report.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build native libs
        run: python build_scripts/indigo-release-libs.py
      - name: Build wrappers
        run: python build_scripts/indigo-make-by-libs.py --type=python,java
      - name: Test
        run: python api/tests/python/test.py -j junit_report.xml
      - name: Test report
        if: ${{ always() }}
        run: type junit_report.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          comment_title: Unit Test Statistics
          hide_comments: all but latest
          files: junit_report.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build native libs
        run: python build_scripts/indigo-release-libs.py
      - name: Build wrappers
        run: python build_scripts/indigo-make-by-libs.py --type=python,java
      - name: Test
        run: python api/tests/python/test.py -j junit_report.xml
      - name: Test report
        if: ${{ always() }}
        run: cat junit_report.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results
          comment_title: Unit Test Statistics
          hide_comments: all but latest
          files: junit_report.xml
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
