name: CI

on: [ push ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build native libs
        run: python build_scripts/indigo-release-libs.py
      - name: Build wrappers
        run: python build_scripts/indigo-make-by-libs.py --type=python
      - name: Test
        run: python api/tests/python/test.py -j junit_report.xml
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build native libs
        run: python build_scripts/indigo-release-libs.py
      - name: Build wrappers
        run: python build_scripts/indigo-make-by-libs.py --type=python
      - name: Test
        run: python api/tests/python/test.py -j junit_report.xml
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build native libs
        run: python build_scripts/indigo-release-libs.py
      - name: Build wrappers
        run: python build_scripts/indigo-make-by-libs.py --type=python
      - name: Test
        run: python api/tests/python/test.py -j junit_report.xml
