name: Indigo CI

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    container: epmlsop/indigo-tester:latest
    steps:
      - name: Check gpg key import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
        run: |
          echo SHELL=$SHELL
          echo BASH_VERSION=$BASH_VERSION
          env
          apt install -y gnupg
          echo ${GPG_PRIVATE_KEY} > gpg.key
          cat gpg.key
          gpg --batch --import --verbose gpg.key
          rm gpg.key
          gpg --list-keys
